FROM node:26-alpine AS firstStep 

WORKDIR /frontend 

COPY package*.json ./
RUN npm ci 

COPY . .

RUN npm run build 

FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html 

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]





