services: 

  frontend: 
    build: ./frontend 
    ports: 
     - "3000:80"
    depends_on: 
      - backend 
  
  backend: 
    build: ./backend 
    ports: 
      - "8000:8000"
    environment: 
      DATABASE_URL: ${DATABASE_URL}
    depends_on: 
      db:
        condition: service_healthy
  
  db: 
    image: postgres:16
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - myapplication_postgres_data:/var/lib/postgresql/data
      - ./backend/startTable.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes: 
  myapplication_postgres_data:
